name: docker-compose-actions-workflow
on:
  push:
    paths:
      - backend/**
      - tests/performance-tests/** 
      - .github/workflows/load-test.yml 
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build & Test
        run: cd tests/performance-tests && docker-compose up -d --build --force-recreate