name: Web & Api Tests
on:
  push:
    paths:
      - web-app/**
      - tests/web-tests/** 
      - .github/workflows/web-test.yml 
  pull_request:
    branches: [ main, master ]

env:
  TEST_ENV: local
  CI: true

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  run-web-test:
    name: Run Web & Api Tests
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*    
    - name: Install Docker using Docker's official script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Start Local Dev Server
      run: cd web-app && source start-server.sh &        
    - name: Install dependencies
      run: cd tests/web-tests && npm ci
    - name: Install Playwright Browsers
      run: cd tests/web-tests && npx playwright install --with-deps
    - name: Run Static Code Linting Checks
      run: cd tests/web-tests && npm run lint
    - name: Run Playwright tests
      run: cd tests/web-tests && npm run test:chromium:ci
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: web-tests-report
        path: tests/web-tests/playwright-report/
        retention-days: 30
  
  publish-web-test-report:
    name: Publish Web Test HTML Report
    # using always() is not ideal here, because it would also run if the workflow was cancelled
    if: "success() || needs.test.result == 'failure'"
    needs: [run-web-test]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      # Unique URL path for each workflow run attempt
      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Set Git Hub Actions Bot User
        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Download zipped HTML report
        uses: actions/download-artifact@v4
        with:
          name: web-tests-report
          path: ${{ env.HTML_REPORT_URL_PATH }}
      - name: Push HTML Report
        timeout-minutes: 3
        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
        # this is necessary when this job running at least twice at the same time (e.g. through two pushes at the same time)
        run: |
          git add .
          git commit -m "workflow: add Web Test HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"

          while true; do
            git pull --rebase
            if [ $? -ne 0 ]; then
              echo "Failed to rebase. Please review manually."
              exit 1
            fi

            git push
            if [ $? -eq 0 ]; then
              echo "Successfully pushed HTML report to repo."
              exit 0
            fi
          done
      - name: Output Report URL as Worfklow Annotation
        run: |
          FULL_HTML_REPORT_URL=https://vamsidarbhamulla.github.io/full-stack-tests-demo/$HTML_REPORT_URL_PATH

          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"