name: Web & Api Tests
on:
  push:
    paths:
      - web-app/**
      - tests/web-tests/** 
      - .github/workflows/web-test.yml 
  pull_request:
    branches: [ main, master ]

env:
  TEST_ENV: test
  CI: true

jobs:
  run-web-test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*    
    - name: Install Docker using Docker's official script
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Start Local Dev Server
      run: cd web-app && source start-server.sh &        
    - name: Install dependencies
      run: cd tests/web-tests && npm ci
    - name: Install Playwright Browsers
      run: cd tests/web-tests && npx playwright install --with-deps
    - name: Run Playwright tests
      run: cd tests/web-tests && npm run test:chromium:ci
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: web-tests-report
        path: tests/web-tests/playwright-report/
        retention-days: 30